--- #YAML:1.0
name:                WWW-Scraper-ISBN-Siciliano_Driver
version:             0.02
abstract:            Search driver for Siciliano's online catalog.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    HTTP::Request::Common:         1.26
    LWP:                           5.805
    Test::More:                    0.62
    WWW::Scraper:                  3.05
    WWW::Scraper::ISBN:            0.25
    WWW::Scraper::ISBN::Driver:    0.18
    WWW::Scraper::ISBN::Record:    0.17
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Joenio Costa <joenio@perl.org.br>
