# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scraper-ISBN-Siciliano_Driver
version:      0.01
version_from: lib/WWW/Scraper/ISBN/Siciliano_Driver.pm
installdirs:  site
requires:
    HTTP::Request::Common:         1.26
    LWP:                           5.805
    Test::More:                    0.62
    WWW::Scraper:                  3.05
    WWW::Scraper::ISBN:            0.25
    WWW::Scraper::ISBN::Driver:    0.18
    WWW::Scraper::ISBN::Record:    0.17

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
